# Generated by Django 4.2.16 on 2026-04-13 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Ism Familiya')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('subscription_start', models.DateField(blank=True, null=True, verbose_name='Obuna boshlanishi')),
                ('subscription_end', models.DateField(blank=True, null=True, verbose_name='Obuna tugashi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism Familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami xaridlar')),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami qarz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Umumiy summa')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="To'langan")),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Qolgan qarz')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Muddat')),
                ('status', models.CharField(choices=[("to'lanmagan", "To'lanmagan"), ("qisman to'langan", "Qisman to'langan"), ("to'langan", "To'langan")], default="to'lanmagan", max_length=30, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='dokon.customer')),
            ],
            options={
                'verbose_name': 'Qarz',
                'verbose_name_plural': 'Qarzlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('category', models.CharField(choices=[('Erkaklar kiyimi', 'Erkaklar kiyimi'), ('Ayollar kiyimi', 'Ayollar kiyimi'), ('Bolalar kiyimi', 'Bolalar kiyimi'), ('Poyabzal', 'Poyabzal'), ('Aksessuarlar', 'Aksessuarlar'), ('Boshqa', 'Boshqa')], max_length=50, verbose_name='Kategoriya')),
                ('brand', models.CharField(max_length=100, verbose_name='Brend')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tan narxi')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sotuv narxi')),
                ('colors', models.JSONField(default=list, verbose_name='Ranglar')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='Barcode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jami summa')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="To'langan summa")),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Chegirma')),
                ('payment_method', models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Karta'), ('nasiya', 'Nasiya')], default='naqd', max_length=10, verbose_name="To'lov usuli")),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='dokon.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=200, verbose_name='Ism Familiya')),
                ('store_name', models.CharField(default="Kiyim Do'koni", max_length=200, verbose_name="Do'kon nomi")),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('work_hours', models.CharField(blank=True, max_length=50, verbose_name='Ish vaqti')),
                ('currency', models.CharField(default="so'm", max_length=20, verbose_name='Valyuta')),
                ('low_stock_alert', models.PositiveIntegerField(default=10, verbose_name='Kam qolgan ogohlantirish')),
                ('avatar', models.CharField(default='🏪', max_length=10, verbose_name='Avatar emoji')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Do'kon profili",
                'verbose_name_plural': "Do'kon profillari",
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('size', models.CharField(max_length=10, verbose_name="O'lcham")),
                ('color', models.CharField(max_length=50, verbose_name='Rang')),
                ('quantity', models.PositiveIntegerField(verbose_name='Soni')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Narx')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='dokon.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dokon.sale')),
            ],
            options={
                'verbose_name': 'Sotuv elementi',
                'verbose_name_plural': 'Sotuv elementlari',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Ijara', 'Ijara'), ("Kommunal to'lovlar", "Kommunal to'lovlar"), ('Ish haqi', 'Ish haqi'), ('Transport', 'Transport'), ('Mahsulot xaridi', 'Mahsulot xaridi'), ("Ta'mirlash", "Ta'mirlash"), ('Marketing', 'Marketing'), ('Boshqa', 'Boshqa')], max_length=50, verbose_name='Kategoriya')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Summa')),
                ('date', models.DateField(verbose_name='Sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="To'lov summasi")),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dokon.debt')),
            ],
            options={
                'verbose_name': "Qarz to'lovi",
                'verbose_name_plural': "Qarz to'lovlari",
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='debt',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='dokon.sale'),
        ),
        migrations.AddField(
            model_name='debt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name="O'lcham")),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Soni')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='dokon.product')),
            ],
            options={
                'verbose_name': "O'lcham",
                'verbose_name_plural': "O'lchamlar",
                'unique_together': {('product', 'size')},
            },
        ),
    ]
