# Generated by Django 6.0.4 on 2026-04-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokon', '0002_alter_customer_options_alter_debt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='return_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='returned_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
